(setv bloggers
  '((paultag            2016-05-30 (("http://blog.pault.ag/rss" :rss)
                                    ("http://notes.pault.ag/feeds/all-en.rss.xml" :rss)))
    (konklone           2016-05-30 (("https://konklone.com/rss.xml" :rss)))
    (tjl                2016-05-30 (("https://tomlee.wtf/feed/" :rss)))
    (zmaril             2016-05-30 (("https://zacharymaril.com/feed/" :rss)))
    (bjames             2016-05-30 (("http://thisweekiate.tumblr.com/rss" :rss)))
    (ajschumacher       2016-05-30 (("http://planspace.org/rss.xml" :rss)))
    (danielschuman      2016-05-30 (("https://medium.com/feed/@danielschuman" :rss)
                                    ("http://congressionaldata.org/feed/" :rss)))
    (jacks              2016-10-03 (("http://linzjax.github.io/feed.xml" :rss)))))
